#!/usr/bin/env python
import open3d as o3d

# 读取PCD文件
pcd = o3d.io.read_point_cloud("points_1735036773_440928.pcd")

# 可视化点云
o3d.visualization.draw_geometries([pcd], 
                                  window_name="Point Cloud",
                                  width=1024,
                                  height=768,
                                  point_show_normal=False)  # 关闭法线显示（若有）
