// Generated by gencpp from file syn_cpp/BboxData.msg
// DO NOT EDIT!


#ifndef SYN_CPP_MESSAGE_BBOXDATA_H
#define SYN_CPP_MESSAGE_BBOXDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace syn_cpp
{
template <class ContainerAllocator>
struct BboxData_
{
  typedef BboxData_<ContainerAllocator> Type;

  BboxData_()
    : header()
    , target_info()  {
    }
  BboxData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , target_info(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _target_info_type;
  _target_info_type target_info;





  typedef boost::shared_ptr< ::syn_cpp::BboxData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::syn_cpp::BboxData_<ContainerAllocator> const> ConstPtr;

}; // struct BboxData_

typedef ::syn_cpp::BboxData_<std::allocator<void> > BboxData;

typedef boost::shared_ptr< ::syn_cpp::BboxData > BboxDataPtr;
typedef boost::shared_ptr< ::syn_cpp::BboxData const> BboxDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::syn_cpp::BboxData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::syn_cpp::BboxData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::syn_cpp::BboxData_<ContainerAllocator1> & lhs, const ::syn_cpp::BboxData_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.target_info == rhs.target_info;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::syn_cpp::BboxData_<ContainerAllocator1> & lhs, const ::syn_cpp::BboxData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace syn_cpp

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::syn_cpp::BboxData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::syn_cpp::BboxData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::syn_cpp::BboxData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::syn_cpp::BboxData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::syn_cpp::BboxData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::syn_cpp::BboxData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::syn_cpp::BboxData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb9a702374fae8e6b561aa485440b9bb";
  }

  static const char* value(const ::syn_cpp::BboxData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb9a702374fae8e6ULL;
  static const uint64_t static_value2 = 0xb561aa485440b9bbULL;
};

template<class ContainerAllocator>
struct DataType< ::syn_cpp::BboxData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "syn_cpp/BboxData";
  }

  static const char* value(const ::syn_cpp::BboxData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::syn_cpp::BboxData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# BboxData.msg\n"
"Header header                  # ROS 标准 Header（包含时间戳和坐标系）\n"
"float32[] target_info          # 6 个元素，格式: [id, x1, y1, x2, y2, status]\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::syn_cpp::BboxData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::syn_cpp::BboxData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.target_info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BboxData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::syn_cpp::BboxData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::syn_cpp::BboxData_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "target_info[]" << std::endl;
    for (size_t i = 0; i < v.target_info.size(); ++i)
    {
      s << indent << "  target_info[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.target_info[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SYN_CPP_MESSAGE_BBOXDATA_H
